name: Regenerate Stock Fetch Workflow

permissions:
  actions: write

on:
  push:
    paths:
      - cph_symbols.txt
      - gen_workflow.py
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run generator
        run: python gen_workflow.py

      - name: Commit and push workflow file
        env:
          TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          git config user.name "automation-bot"
          git config user.email "bot@example.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .github/workflows/fetch_stocks.yml
          git diff --cached --quiet || git commit -m "🔄 Auto-generate fetch_stocks.yml"
          git push
